-- Reference-data seed: well-known taxonomy entries. Idempotent; respects dedupe and the skill/technology cross-category lock.
INSERT INTO public.programming_languages(language_name, normalized_name)
SELECT v, public.taxonomy_key(v) FROM unnest(ARRAY['HTML','CSS','Clojure','Nim','Mojo','Hack','Sass','Groovy']) v
WHERE NOT EXISTS (SELECT 1 FROM public.programming_languages p WHERE p.normalized_name = public.taxonomy_key(v));

INSERT INTO public.technical_skills(skill_name)
SELECT v FROM unnest(ARRAY[
'Frontend Development','Backend Development','Full Stack Development','Mobile Development','iOS Development','Android Development','Web Development','Game Development','Embedded Systems','Microservices Architecture','RESTful API Design','GraphQL API Design','API Development','Event-Driven Architecture','Distributed Systems','Object-Oriented Programming','Functional Programming','Test-Driven Development','Unit Testing','Integration Testing','Test Automation','Quality Assurance','Performance Optimization','Database Design','Database Administration','Query Optimization','Data Engineering','Data Warehousing','Data Pipelines','Data Governance','Data Quality','Data Analysis','Data Science','Business Intelligence','Statistical Analysis','A/B Testing','Predictive Modeling','Feature Engineering','Natural Language Processing','Computer Vision','Large Language Models','Generative AI','Reinforcement Learning','Recommender Systems','Time Series Analysis','Model Deployment','LLM Fine-Tuning','AI Agents','Cloud Migration','Infrastructure as Code','Site Reliability Engineering','DevOps','Containerization','Container Orchestration','Serverless Architecture','Network Engineering','Network Security','Cybersecurity','Penetration Testing','Vulnerability Management','Identity and Access Management','Cryptography','Incident Response','Security Operations','Cloud Security','Application Security','Compliance','Monitoring and Observability','Linux Administration','Systems Administration','Technical Support','UI Design','UX Design','UX Research','Accessibility','Technical Writing','Agile Methodologies','Scrum','Product Management','Project Management','Business Analysis','Requirements Gathering','Solution Architecture','Enterprise Architecture','Blockchain Development','Smart Contracts','Automation','Scripting','Version Control','Code Review','Software Architecture'
]) v
WHERE NOT EXISTS (SELECT 1 FROM public.technologies t WHERE t.normalized_name = public.taxonomy_key(v))
ON CONFLICT (normalized_name) DO NOTHING;

INSERT INTO public.technologies(technology_name, technology_category)
SELECT v, c FROM (VALUES
('React','Development'),('Next.js','Development'),('Vue.js','Development'),('Angular','Development'),('Svelte','Development'),('Node.js','Development'),('Express','Development'),('NestJS','Development'),('FastAPI','Development'),('Django','Development'),('Flask','Development'),('Spring Boot','Development'),('.NET','Development'),('ASP.NET Core','Development'),('Ruby on Rails','Development'),('Laravel','Development'),('React Native','Development'),('Flutter','Development'),('Tailwind CSS','Development'),('Redux','Development'),('GraphQL','Development'),('gRPC','Development'),('Git','Development'),('GitLab','Development'),('Bitbucket','Development'),('Postman','Development'),('Swagger','Development'),('Visual Studio Code','Development'),('IntelliJ IDEA','Development'),('Xcode','Development'),('Android Studio','Development'),('Jest','Development'),('Cypress','Development'),('Playwright','Development'),('Selenium','Development'),('Pytest','Development'),('JUnit','Development'),('Storybook','Development'),('Vite','Development'),('Webpack','Development'),
('PostgreSQL','Data Platform'),('MySQL','Data Platform'),('Microsoft SQL Server','Data Platform'),('Oracle Database','Data Platform'),('SQLite','Data Platform'),('MongoDB','Data Platform'),('Redis','Data Platform'),('Elasticsearch','Data Platform'),('Cassandra','Data Platform'),('DynamoDB','Data Platform'),('Neo4j','Data Platform'),('Supabase','Data Platform'),('Firebase','Data Platform'),('BigQuery','Data Platform'),('Amazon Redshift','Data Platform'),('ClickHouse','Data Platform'),('dbt','Data Platform'),('Fivetran','Data Platform'),('Apache Flink','Data Platform'),('Apache Hadoop','Data Platform'),('Apache Iceberg','Data Platform'),('Delta Lake','Data Platform'),('Informatica','Data Platform'),('Talend','Data Platform'),('Pinecone','Data Platform'),('Weaviate','Data Platform'),
('Pandas','Analytics'),('NumPy','Analytics'),('Jupyter','Analytics'),('Excel','Analytics'),('Qlik','Analytics'),('Google Analytics','Analytics'),('Amplitude','Analytics'),('SAS','Analytics'),('SPSS','Analytics'),('Metabase','Analytics'),
('Scikit-learn','AI'),('Keras','AI'),('JAX','AI'),('Hugging Face','AI'),('LlamaIndex','AI'),('MLflow','AI'),('Kubeflow','AI'),('Amazon SageMaker','AI'),('Vertex AI','AI'),('Azure Machine Learning','AI'),('XGBoost','AI'),('LightGBM','AI'),('OpenCV','AI'),('spaCy','AI'),('Gemini','AI'),('Llama','AI'),('Weights & Biases','AI'),
('Ansible','Infrastructure'),('Helm','Infrastructure'),('Argo CD','Infrastructure'),('GitLab CI','Infrastructure'),('CircleCI','Infrastructure'),('Linux','Infrastructure'),('Nginx','Infrastructure'),('Prometheus','Infrastructure'),('Grafana','Infrastructure'),('Datadog','Infrastructure'),('New Relic','Infrastructure'),('Pulumi','Infrastructure'),('VMware','Infrastructure'),('RabbitMQ','Infrastructure'),('Istio','Infrastructure'),
('AWS Lambda','Cloud'),('Amazon S3','Cloud'),('Amazon EC2','Cloud'),('Amazon EKS','Cloud'),('Azure DevOps','Cloud'),('Azure Functions','Cloud'),('Google Kubernetes Engine','Cloud'),('Cloudflare','Cloud'),('Vercel','Cloud'),('Heroku','Cloud'),
('Okta','Security'),('Palo Alto Networks','Security'),('Wireshark','Security'),('Burp Suite','Security'),('Metasploit','Security'),('Nessus','Security'),('HashiCorp Vault','Security'),('Snyk','Security'),
('Slack','Other'),('Microsoft Teams','Other'),('Notion','Other'),('Asana','Other'),('Trello','Other'),('Linear','Other'),('Miro','Other'),('Salesforce','Other'),('SAP','Other'),('HubSpot','Other'),('Zendesk','Other')
) s(v, c)
WHERE NOT EXISTS (SELECT 1 FROM public.technical_skills k WHERE k.normalized_name = public.taxonomy_key(v))
ON CONFLICT (normalized_name) DO NOTHING;

INSERT INTO public.soft_skills(soft_skill_name)
SELECT v FROM unnest(ARRAY[
'Active Listening','Empathy','Conflict Resolution','Negotiation','Presentation Skills','Public Speaking','Written Communication','Cross-Functional Collaboration','Mentoring','Coaching','Creativity','Innovation','Strategic Thinking','Analytical Thinking','Prioritization','Self-Motivation','Resilience','Work Ethic','Curiosity','Continuous Learning','Customer Focus','Influencing','Delegation','Team Building','Remote Collaboration','Cultural Awareness','Patience','Flexibility','Dependability','Ownership','Stress Management','Facilitation','Relationship Building','Giving Feedback','Receiving Feedback'
]) v
ON CONFLICT (normalized_name) DO NOTHING;