/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CommunityGuidelinesRouteImport } from './routes/community-guidelines'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HelpRouteImport } from './routes/help'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as AuthenticatedCandidateRouteImport } from './routes/_authenticated/candidate'
import { Route as AuthenticatedRecruiterRouteImport } from './routes/_authenticated/recruiter'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedCandidateIndexRouteImport } from './routes/_authenticated/candidate/index'
import { Route as AuthenticatedCandidateAnalyticsRouteImport } from './routes/_authenticated/candidate/analytics'
import { Route as AuthenticatedCandidateApplicationsRouteImport } from './routes/_authenticated/candidate/applications'
import { Route as AuthenticatedCandidateCareerRouteImport } from './routes/_authenticated/candidate/career'
import { Route as AuthenticatedCandidateDashboardRouteImport } from './routes/_authenticated/candidate/dashboard'
import { Route as AuthenticatedCandidateJobsRouteImport } from './routes/_authenticated/candidate/jobs'
import { Route as AuthenticatedCandidateMessagesRouteImport } from './routes/_authenticated/candidate/messages'
import { Route as AuthenticatedCandidateNotificationsRouteImport } from './routes/_authenticated/candidate/notifications'
import { Route as AuthenticatedCandidateOnboardingRouteImport } from './routes/_authenticated/candidate/onboarding'
import { Route as AuthenticatedCandidateProfileRouteImport } from './routes/_authenticated/candidate/profile'
import { Route as AuthenticatedCandidateRecommendationsRouteImport } from './routes/_authenticated/candidate/recommendations'
import { Route as AuthenticatedCandidateSavedJobsRouteImport } from './routes/_authenticated/candidate/saved-jobs'
import { Route as AuthenticatedCandidateSettingsRouteImport } from './routes/_authenticated/candidate/settings'
import { Route as AuthenticatedNotificationsIndexRouteImport } from './routes/_authenticated/notifications.index'
import { Route as AuthenticatedNotificationsIdRouteImport } from './routes/_authenticated/notifications.$id'
import { Route as AuthenticatedRecruiterIndexRouteImport } from './routes/_authenticated/recruiter/index'
import { Route as AuthenticatedRecruiterAnalyticsRouteImport } from './routes/_authenticated/recruiter/analytics'
import { Route as AuthenticatedRecruiterApplicationsRouteImport } from './routes/_authenticated/recruiter/applications'
import { Route as AuthenticatedRecruiterCandidatesRouteImport } from './routes/_authenticated/recruiter/candidates'
import { Route as AuthenticatedRecruiterCompanyRouteImport } from './routes/_authenticated/recruiter/company'
import { Route as AuthenticatedRecruiterDashboardRouteImport } from './routes/_authenticated/recruiter/dashboard'
import { Route as AuthenticatedRecruiterJobsRouteImport } from './routes/_authenticated/recruiter/jobs'
import { Route as AuthenticatedRecruiterMessagesRouteImport } from './routes/_authenticated/recruiter/messages'
import { Route as AuthenticatedRecruiterNotificationsRouteImport } from './routes/_authenticated/recruiter/notifications'
import { Route as AuthenticatedRecruiterOnboardingRouteImport } from './routes/_authenticated/recruiter/onboarding'
import { Route as AuthenticatedRecruiterPipelineRouteImport } from './routes/_authenticated/recruiter/pipeline'
import { Route as AuthenticatedRecruiterProfileRouteImport } from './routes/_authenticated/recruiter/profile'
import { Route as AuthenticatedRecruiterRecommendationsRouteImport } from './routes/_authenticated/recruiter/recommendations'
import { Route as AuthenticatedRecruiterSettingsRouteImport } from './routes/_authenticated/recruiter/settings'
import { Route as AuthenticatedCandidateApplicationsIndexRouteImport } from './routes/_authenticated/candidate/applications.index'
import { Route as AuthenticatedCandidateApplicationsIdRouteImport } from './routes/_authenticated/candidate/applications.$id'
import { Route as AuthenticatedCandidateJobsIndexRouteImport } from './routes/_authenticated/candidate/jobs.index'
import { Route as AuthenticatedCandidateJobsIdRouteImport } from './routes/_authenticated/candidate/jobs.$id'
import { Route as AuthenticatedCandidateJobsCompareRouteImport } from './routes/_authenticated/candidate/jobs.compare'
import { Route as AuthenticatedCandidateJobsSavedRouteImport } from './routes/_authenticated/candidate/jobs.saved'
import { Route as AuthenticatedCandidateMessagesIndexRouteImport } from './routes/_authenticated/candidate/messages.index'
import { Route as AuthenticatedCandidateMessagesConversationIdRouteImport } from './routes/_authenticated/candidate/messages.$conversationId'
import { Route as AuthenticatedCandidateNotificationsIndexRouteImport } from './routes/_authenticated/candidate/notifications.index'
import { Route as AuthenticatedCandidateNotificationsIdRouteImport } from './routes/_authenticated/candidate/notifications.$id'
import { Route as AuthenticatedRecruiterApplicationsIndexRouteImport } from './routes/_authenticated/recruiter/applications.index'
import { Route as AuthenticatedRecruiterApplicationsIdRouteImport } from './routes/_authenticated/recruiter/applications.$id'
import { Route as AuthenticatedRecruiterCandidatesIndexRouteImport } from './routes/_authenticated/recruiter/candidates.index'
import { Route as AuthenticatedRecruiterCandidatesIdRouteImport } from './routes/_authenticated/recruiter/candidates.$id'
import { Route as AuthenticatedRecruiterCandidatesCompareRouteImport } from './routes/_authenticated/recruiter/candidates.compare'
import { Route as AuthenticatedRecruiterCandidatesSavedRouteImport } from './routes/_authenticated/recruiter/candidates.saved'
import { Route as AuthenticatedRecruiterJobsIndexRouteImport } from './routes/_authenticated/recruiter/jobs.index'
import { Route as AuthenticatedRecruiterJobsCreateRouteImport } from './routes/_authenticated/recruiter/jobs.create'
import { Route as AuthenticatedRecruiterMessagesIndexRouteImport } from './routes/_authenticated/recruiter/messages.index'
import { Route as AuthenticatedRecruiterMessagesConversationIdRouteImport } from './routes/_authenticated/recruiter/messages.$conversationId'
import { Route as AuthenticatedRecruiterNotificationsIndexRouteImport } from './routes/_authenticated/recruiter/notifications.index'
import { Route as AuthenticatedRecruiterNotificationsIdRouteImport } from './routes/_authenticated/recruiter/notifications.$id'
import { Route as AuthenticatedRecruiterPipelineIndexRouteImport } from './routes/_authenticated/recruiter/pipeline.index'
import { Route as AuthenticatedRecruiterPipelineJobIdRouteImport } from './routes/_authenticated/recruiter/pipeline.$jobId'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as AuthenticatedRecruiterJobsIdIndexRouteImport } from './routes/_authenticated/recruiter/jobs.$id.index'
import { Route as AuthenticatedRecruiterJobsIdEditRouteImport } from './routes/_authenticated/recruiter/jobs.$id.edit'
import { Route as AuthenticatedRecruiterJobsIdPreviewRouteImport } from './routes/_authenticated/recruiter/jobs.$id.preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityGuidelinesRoute = CommunityGuidelinesRouteImport.update({
  id: '/community-guidelines',
  path: '/community-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCandidateRoute = AuthenticatedCandidateRouteImport.update({
  id: '/candidate',
  path: '/candidate',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecruiterRoute = AuthenticatedRecruiterRouteImport.update({
  id: '/recruiter',
  path: '/recruiter',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/admin/analytics',
    path: '/admin/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/admin/reports',
    path: '/admin/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCandidateIndexRoute =
  AuthenticatedCandidateIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCandidateRoute,
  } as any)
const AuthenticatedCandidateAnalyticsRoute =
  AuthenticatedCandidateAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedCandidateRoute,
  } as any)
const AuthenticatedCandidateApplicationsRoute =
  AuthenticatedCandidateApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedCandidateRoute,
  } as any)
const AuthenticatedCandidateCareerRoute =
  AuthenticatedCandidateCareerRouteImport.update({
    id: '/career',
    path: '/career',
    getParentRoute: () => AuthenticatedCandidateRoute,
  } as any)
const AuthenticatedCandidateDashboardRoute =
  AuthenticatedCandidateDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedCandidateRoute,
  } as any)
const AuthenticatedCandidateJobsRoute =
  AuthenticatedCandidateJobsRouteImport.update({
    id: '/jobs',
    path: '/jobs',
    getParentRoute: () => AuthenticatedCandidateRoute,
  } as any)
const AuthenticatedCandidateMessagesRoute =
  AuthenticatedCandidateMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedCandidateRoute,
  } as any)
const AuthenticatedCandidateNotificationsRoute =
  AuthenticatedCandidateNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedCandidateRoute,
  } as any)
const AuthenticatedCandidateOnboardingRoute =
  AuthenticatedCandidateOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedCandidateRoute,
  } as any)
const AuthenticatedCandidateProfileRoute =
  AuthenticatedCandidateProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedCandidateRoute,
  } as any)
const AuthenticatedCandidateRecommendationsRoute =
  AuthenticatedCandidateRecommendationsRouteImport.update({
    id: '/recommendations',
    path: '/recommendations',
    getParentRoute: () => AuthenticatedCandidateRoute,
  } as any)
const AuthenticatedCandidateSavedJobsRoute =
  AuthenticatedCandidateSavedJobsRouteImport.update({
    id: '/saved-jobs',
    path: '/saved-jobs',
    getParentRoute: () => AuthenticatedCandidateRoute,
  } as any)
const AuthenticatedCandidateSettingsRoute =
  AuthenticatedCandidateSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedCandidateRoute,
  } as any)
const AuthenticatedNotificationsIndexRoute =
  AuthenticatedNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationsIdRoute =
  AuthenticatedNotificationsIdRouteImport.update({
    id: '/notifications/$id',
    path: '/notifications/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecruiterIndexRoute =
  AuthenticatedRecruiterIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRecruiterRoute,
  } as any)
const AuthenticatedRecruiterAnalyticsRoute =
  AuthenticatedRecruiterAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedRecruiterRoute,
  } as any)
const AuthenticatedRecruiterApplicationsRoute =
  AuthenticatedRecruiterApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRecruiterRoute,
  } as any)
const AuthenticatedRecruiterCandidatesRoute =
  AuthenticatedRecruiterCandidatesRouteImport.update({
    id: '/candidates',
    path: '/candidates',
    getParentRoute: () => AuthenticatedRecruiterRoute,
  } as any)
const AuthenticatedRecruiterCompanyRoute =
  AuthenticatedRecruiterCompanyRouteImport.update({
    id: '/company',
    path: '/company',
    getParentRoute: () => AuthenticatedRecruiterRoute,
  } as any)
const AuthenticatedRecruiterDashboardRoute =
  AuthenticatedRecruiterDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRecruiterRoute,
  } as any)
const AuthenticatedRecruiterJobsRoute =
  AuthenticatedRecruiterJobsRouteImport.update({
    id: '/jobs',
    path: '/jobs',
    getParentRoute: () => AuthenticatedRecruiterRoute,
  } as any)
const AuthenticatedRecruiterMessagesRoute =
  AuthenticatedRecruiterMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedRecruiterRoute,
  } as any)
const AuthenticatedRecruiterNotificationsRoute =
  AuthenticatedRecruiterNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRecruiterRoute,
  } as any)
const AuthenticatedRecruiterOnboardingRoute =
  AuthenticatedRecruiterOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedRecruiterRoute,
  } as any)
const AuthenticatedRecruiterPipelineRoute =
  AuthenticatedRecruiterPipelineRouteImport.update({
    id: '/pipeline',
    path: '/pipeline',
    getParentRoute: () => AuthenticatedRecruiterRoute,
  } as any)
const AuthenticatedRecruiterProfileRoute =
  AuthenticatedRecruiterProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedRecruiterRoute,
  } as any)
const AuthenticatedRecruiterRecommendationsRoute =
  AuthenticatedRecruiterRecommendationsRouteImport.update({
    id: '/recommendations',
    path: '/recommendations',
    getParentRoute: () => AuthenticatedRecruiterRoute,
  } as any)
const AuthenticatedRecruiterSettingsRoute =
  AuthenticatedRecruiterSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRecruiterRoute,
  } as any)
const AuthenticatedCandidateApplicationsIndexRoute =
  AuthenticatedCandidateApplicationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCandidateApplicationsRoute,
  } as any)
const AuthenticatedCandidateApplicationsIdRoute =
  AuthenticatedCandidateApplicationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCandidateApplicationsRoute,
  } as any)
const AuthenticatedCandidateJobsIndexRoute =
  AuthenticatedCandidateJobsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCandidateJobsRoute,
  } as any)
const AuthenticatedCandidateJobsIdRoute =
  AuthenticatedCandidateJobsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCandidateJobsRoute,
  } as any)
const AuthenticatedCandidateJobsCompareRoute =
  AuthenticatedCandidateJobsCompareRouteImport.update({
    id: '/compare',
    path: '/compare',
    getParentRoute: () => AuthenticatedCandidateJobsRoute,
  } as any)
const AuthenticatedCandidateJobsSavedRoute =
  AuthenticatedCandidateJobsSavedRouteImport.update({
    id: '/saved',
    path: '/saved',
    getParentRoute: () => AuthenticatedCandidateJobsRoute,
  } as any)
const AuthenticatedCandidateMessagesIndexRoute =
  AuthenticatedCandidateMessagesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCandidateMessagesRoute,
  } as any)
const AuthenticatedCandidateMessagesConversationIdRoute =
  AuthenticatedCandidateMessagesConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AuthenticatedCandidateMessagesRoute,
  } as any)
const AuthenticatedCandidateNotificationsIndexRoute =
  AuthenticatedCandidateNotificationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCandidateNotificationsRoute,
  } as any)
const AuthenticatedCandidateNotificationsIdRoute =
  AuthenticatedCandidateNotificationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCandidateNotificationsRoute,
  } as any)
const AuthenticatedRecruiterApplicationsIndexRoute =
  AuthenticatedRecruiterApplicationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRecruiterApplicationsRoute,
  } as any)
const AuthenticatedRecruiterApplicationsIdRoute =
  AuthenticatedRecruiterApplicationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedRecruiterApplicationsRoute,
  } as any)
const AuthenticatedRecruiterCandidatesIndexRoute =
  AuthenticatedRecruiterCandidatesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRecruiterCandidatesRoute,
  } as any)
const AuthenticatedRecruiterCandidatesIdRoute =
  AuthenticatedRecruiterCandidatesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedRecruiterCandidatesRoute,
  } as any)
const AuthenticatedRecruiterCandidatesCompareRoute =
  AuthenticatedRecruiterCandidatesCompareRouteImport.update({
    id: '/compare',
    path: '/compare',
    getParentRoute: () => AuthenticatedRecruiterCandidatesRoute,
  } as any)
const AuthenticatedRecruiterCandidatesSavedRoute =
  AuthenticatedRecruiterCandidatesSavedRouteImport.update({
    id: '/saved',
    path: '/saved',
    getParentRoute: () => AuthenticatedRecruiterCandidatesRoute,
  } as any)
const AuthenticatedRecruiterJobsIndexRoute =
  AuthenticatedRecruiterJobsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRecruiterJobsRoute,
  } as any)
const AuthenticatedRecruiterJobsCreateRoute =
  AuthenticatedRecruiterJobsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedRecruiterJobsRoute,
  } as any)
const AuthenticatedRecruiterMessagesIndexRoute =
  AuthenticatedRecruiterMessagesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRecruiterMessagesRoute,
  } as any)
const AuthenticatedRecruiterMessagesConversationIdRoute =
  AuthenticatedRecruiterMessagesConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AuthenticatedRecruiterMessagesRoute,
  } as any)
const AuthenticatedRecruiterNotificationsIndexRoute =
  AuthenticatedRecruiterNotificationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRecruiterNotificationsRoute,
  } as any)
const AuthenticatedRecruiterNotificationsIdRoute =
  AuthenticatedRecruiterNotificationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedRecruiterNotificationsRoute,
  } as any)
const AuthenticatedRecruiterPipelineIndexRoute =
  AuthenticatedRecruiterPipelineIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRecruiterPipelineRoute,
  } as any)
const AuthenticatedRecruiterPipelineJobIdRoute =
  AuthenticatedRecruiterPipelineJobIdRouteImport.update({
    id: '/$jobId',
    path: '/$jobId',
    getParentRoute: () => AuthenticatedRecruiterPipelineRoute,
  } as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedRecruiterJobsIdIndexRoute =
  AuthenticatedRecruiterJobsIdIndexRouteImport.update({
    id: '/$id/',
    path: '/$id/',
    getParentRoute: () => AuthenticatedRecruiterJobsRoute,
  } as any)
const AuthenticatedRecruiterJobsIdEditRoute =
  AuthenticatedRecruiterJobsIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthenticatedRecruiterJobsRoute,
  } as any)
const AuthenticatedRecruiterJobsIdPreviewRoute =
  AuthenticatedRecruiterJobsIdPreviewRouteImport.update({
    id: '/$id/preview',
    path: '/$id/preview',
    getParentRoute: () => AuthenticatedRecruiterJobsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/candidate': typeof AuthenticatedCandidateRouteWithChildren
  '/recruiter': typeof AuthenticatedRecruiterRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/candidate/analytics': typeof AuthenticatedCandidateAnalyticsRoute
  '/candidate/applications': typeof AuthenticatedCandidateApplicationsRouteWithChildren
  '/candidate/career': typeof AuthenticatedCandidateCareerRoute
  '/candidate/dashboard': typeof AuthenticatedCandidateDashboardRoute
  '/candidate/jobs': typeof AuthenticatedCandidateJobsRouteWithChildren
  '/candidate/messages': typeof AuthenticatedCandidateMessagesRouteWithChildren
  '/candidate/notifications': typeof AuthenticatedCandidateNotificationsRouteWithChildren
  '/candidate/onboarding': typeof AuthenticatedCandidateOnboardingRoute
  '/candidate/profile': typeof AuthenticatedCandidateProfileRoute
  '/candidate/recommendations': typeof AuthenticatedCandidateRecommendationsRoute
  '/candidate/saved-jobs': typeof AuthenticatedCandidateSavedJobsRoute
  '/candidate/settings': typeof AuthenticatedCandidateSettingsRoute
  '/notifications/$id': typeof AuthenticatedNotificationsIdRoute
  '/recruiter/analytics': typeof AuthenticatedRecruiterAnalyticsRoute
  '/recruiter/applications': typeof AuthenticatedRecruiterApplicationsRouteWithChildren
  '/recruiter/candidates': typeof AuthenticatedRecruiterCandidatesRouteWithChildren
  '/recruiter/company': typeof AuthenticatedRecruiterCompanyRoute
  '/recruiter/dashboard': typeof AuthenticatedRecruiterDashboardRoute
  '/recruiter/jobs': typeof AuthenticatedRecruiterJobsRouteWithChildren
  '/recruiter/messages': typeof AuthenticatedRecruiterMessagesRouteWithChildren
  '/recruiter/notifications': typeof AuthenticatedRecruiterNotificationsRouteWithChildren
  '/recruiter/onboarding': typeof AuthenticatedRecruiterOnboardingRoute
  '/recruiter/pipeline': typeof AuthenticatedRecruiterPipelineRouteWithChildren
  '/recruiter/profile': typeof AuthenticatedRecruiterProfileRoute
  '/recruiter/recommendations': typeof AuthenticatedRecruiterRecommendationsRoute
  '/recruiter/settings': typeof AuthenticatedRecruiterSettingsRoute
  '/candidate/': typeof AuthenticatedCandidateIndexRoute
  '/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/recruiter/': typeof AuthenticatedRecruiterIndexRoute
  '/candidate/applications/$id': typeof AuthenticatedCandidateApplicationsIdRoute
  '/candidate/jobs/$id': typeof AuthenticatedCandidateJobsIdRoute
  '/candidate/jobs/compare': typeof AuthenticatedCandidateJobsCompareRoute
  '/candidate/jobs/saved': typeof AuthenticatedCandidateJobsSavedRoute
  '/candidate/messages/$conversationId': typeof AuthenticatedCandidateMessagesConversationIdRoute
  '/candidate/notifications/$id': typeof AuthenticatedCandidateNotificationsIdRoute
  '/recruiter/applications/$id': typeof AuthenticatedRecruiterApplicationsIdRoute
  '/recruiter/candidates/$id': typeof AuthenticatedRecruiterCandidatesIdRoute
  '/recruiter/candidates/compare': typeof AuthenticatedRecruiterCandidatesCompareRoute
  '/recruiter/candidates/saved': typeof AuthenticatedRecruiterCandidatesSavedRoute
  '/recruiter/jobs/create': typeof AuthenticatedRecruiterJobsCreateRoute
  '/recruiter/messages/$conversationId': typeof AuthenticatedRecruiterMessagesConversationIdRoute
  '/recruiter/notifications/$id': typeof AuthenticatedRecruiterNotificationsIdRoute
  '/recruiter/pipeline/$jobId': typeof AuthenticatedRecruiterPipelineJobIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/candidate/applications/': typeof AuthenticatedCandidateApplicationsIndexRoute
  '/candidate/jobs/': typeof AuthenticatedCandidateJobsIndexRoute
  '/candidate/messages/': typeof AuthenticatedCandidateMessagesIndexRoute
  '/candidate/notifications/': typeof AuthenticatedCandidateNotificationsIndexRoute
  '/recruiter/applications/': typeof AuthenticatedRecruiterApplicationsIndexRoute
  '/recruiter/candidates/': typeof AuthenticatedRecruiterCandidatesIndexRoute
  '/recruiter/jobs/': typeof AuthenticatedRecruiterJobsIndexRoute
  '/recruiter/messages/': typeof AuthenticatedRecruiterMessagesIndexRoute
  '/recruiter/notifications/': typeof AuthenticatedRecruiterNotificationsIndexRoute
  '/recruiter/pipeline/': typeof AuthenticatedRecruiterPipelineIndexRoute
  '/recruiter/jobs/$id/edit': typeof AuthenticatedRecruiterJobsIdEditRoute
  '/recruiter/jobs/$id/preview': typeof AuthenticatedRecruiterJobsIdPreviewRoute
  '/recruiter/jobs/$id/': typeof AuthenticatedRecruiterJobsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/candidate/analytics': typeof AuthenticatedCandidateAnalyticsRoute
  '/candidate/career': typeof AuthenticatedCandidateCareerRoute
  '/candidate/dashboard': typeof AuthenticatedCandidateDashboardRoute
  '/candidate/onboarding': typeof AuthenticatedCandidateOnboardingRoute
  '/candidate/profile': typeof AuthenticatedCandidateProfileRoute
  '/candidate/recommendations': typeof AuthenticatedCandidateRecommendationsRoute
  '/candidate/saved-jobs': typeof AuthenticatedCandidateSavedJobsRoute
  '/candidate/settings': typeof AuthenticatedCandidateSettingsRoute
  '/notifications/$id': typeof AuthenticatedNotificationsIdRoute
  '/recruiter/analytics': typeof AuthenticatedRecruiterAnalyticsRoute
  '/recruiter/company': typeof AuthenticatedRecruiterCompanyRoute
  '/recruiter/dashboard': typeof AuthenticatedRecruiterDashboardRoute
  '/recruiter/onboarding': typeof AuthenticatedRecruiterOnboardingRoute
  '/recruiter/profile': typeof AuthenticatedRecruiterProfileRoute
  '/recruiter/recommendations': typeof AuthenticatedRecruiterRecommendationsRoute
  '/recruiter/settings': typeof AuthenticatedRecruiterSettingsRoute
  '/candidate': typeof AuthenticatedCandidateIndexRoute
  '/notifications': typeof AuthenticatedNotificationsIndexRoute
  '/recruiter': typeof AuthenticatedRecruiterIndexRoute
  '/candidate/applications/$id': typeof AuthenticatedCandidateApplicationsIdRoute
  '/candidate/jobs/$id': typeof AuthenticatedCandidateJobsIdRoute
  '/candidate/jobs/compare': typeof AuthenticatedCandidateJobsCompareRoute
  '/candidate/jobs/saved': typeof AuthenticatedCandidateJobsSavedRoute
  '/candidate/messages/$conversationId': typeof AuthenticatedCandidateMessagesConversationIdRoute
  '/candidate/notifications/$id': typeof AuthenticatedCandidateNotificationsIdRoute
  '/recruiter/applications/$id': typeof AuthenticatedRecruiterApplicationsIdRoute
  '/recruiter/candidates/$id': typeof AuthenticatedRecruiterCandidatesIdRoute
  '/recruiter/candidates/compare': typeof AuthenticatedRecruiterCandidatesCompareRoute
  '/recruiter/candidates/saved': typeof AuthenticatedRecruiterCandidatesSavedRoute
  '/recruiter/jobs/create': typeof AuthenticatedRecruiterJobsCreateRoute
  '/recruiter/messages/$conversationId': typeof AuthenticatedRecruiterMessagesConversationIdRoute
  '/recruiter/notifications/$id': typeof AuthenticatedRecruiterNotificationsIdRoute
  '/recruiter/pipeline/$jobId': typeof AuthenticatedRecruiterPipelineJobIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/candidate/applications': typeof AuthenticatedCandidateApplicationsIndexRoute
  '/candidate/jobs': typeof AuthenticatedCandidateJobsIndexRoute
  '/candidate/messages': typeof AuthenticatedCandidateMessagesIndexRoute
  '/candidate/notifications': typeof AuthenticatedCandidateNotificationsIndexRoute
  '/recruiter/applications': typeof AuthenticatedRecruiterApplicationsIndexRoute
  '/recruiter/candidates': typeof AuthenticatedRecruiterCandidatesIndexRoute
  '/recruiter/jobs': typeof AuthenticatedRecruiterJobsIndexRoute
  '/recruiter/messages': typeof AuthenticatedRecruiterMessagesIndexRoute
  '/recruiter/notifications': typeof AuthenticatedRecruiterNotificationsIndexRoute
  '/recruiter/pipeline': typeof AuthenticatedRecruiterPipelineIndexRoute
  '/recruiter/jobs/$id/edit': typeof AuthenticatedRecruiterJobsIdEditRoute
  '/recruiter/jobs/$id/preview': typeof AuthenticatedRecruiterJobsIdPreviewRoute
  '/recruiter/jobs/$id': typeof AuthenticatedRecruiterJobsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_authenticated/candidate': typeof AuthenticatedCandidateRouteWithChildren
  '/_authenticated/recruiter': typeof AuthenticatedRecruiterRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/candidate/analytics': typeof AuthenticatedCandidateAnalyticsRoute
  '/_authenticated/candidate/applications': typeof AuthenticatedCandidateApplicationsRouteWithChildren
  '/_authenticated/candidate/career': typeof AuthenticatedCandidateCareerRoute
  '/_authenticated/candidate/dashboard': typeof AuthenticatedCandidateDashboardRoute
  '/_authenticated/candidate/jobs': typeof AuthenticatedCandidateJobsRouteWithChildren
  '/_authenticated/candidate/messages': typeof AuthenticatedCandidateMessagesRouteWithChildren
  '/_authenticated/candidate/notifications': typeof AuthenticatedCandidateNotificationsRouteWithChildren
  '/_authenticated/candidate/onboarding': typeof AuthenticatedCandidateOnboardingRoute
  '/_authenticated/candidate/profile': typeof AuthenticatedCandidateProfileRoute
  '/_authenticated/candidate/recommendations': typeof AuthenticatedCandidateRecommendationsRoute
  '/_authenticated/candidate/saved-jobs': typeof AuthenticatedCandidateSavedJobsRoute
  '/_authenticated/candidate/settings': typeof AuthenticatedCandidateSettingsRoute
  '/_authenticated/notifications/$id': typeof AuthenticatedNotificationsIdRoute
  '/_authenticated/recruiter/analytics': typeof AuthenticatedRecruiterAnalyticsRoute
  '/_authenticated/recruiter/applications': typeof AuthenticatedRecruiterApplicationsRouteWithChildren
  '/_authenticated/recruiter/candidates': typeof AuthenticatedRecruiterCandidatesRouteWithChildren
  '/_authenticated/recruiter/company': typeof AuthenticatedRecruiterCompanyRoute
  '/_authenticated/recruiter/dashboard': typeof AuthenticatedRecruiterDashboardRoute
  '/_authenticated/recruiter/jobs': typeof AuthenticatedRecruiterJobsRouteWithChildren
  '/_authenticated/recruiter/messages': typeof AuthenticatedRecruiterMessagesRouteWithChildren
  '/_authenticated/recruiter/notifications': typeof AuthenticatedRecruiterNotificationsRouteWithChildren
  '/_authenticated/recruiter/onboarding': typeof AuthenticatedRecruiterOnboardingRoute
  '/_authenticated/recruiter/pipeline': typeof AuthenticatedRecruiterPipelineRouteWithChildren
  '/_authenticated/recruiter/profile': typeof AuthenticatedRecruiterProfileRoute
  '/_authenticated/recruiter/recommendations': typeof AuthenticatedRecruiterRecommendationsRoute
  '/_authenticated/recruiter/settings': typeof AuthenticatedRecruiterSettingsRoute
  '/_authenticated/candidate/': typeof AuthenticatedCandidateIndexRoute
  '/_authenticated/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/_authenticated/recruiter/': typeof AuthenticatedRecruiterIndexRoute
  '/_authenticated/candidate/applications/$id': typeof AuthenticatedCandidateApplicationsIdRoute
  '/_authenticated/candidate/jobs/$id': typeof AuthenticatedCandidateJobsIdRoute
  '/_authenticated/candidate/jobs/compare': typeof AuthenticatedCandidateJobsCompareRoute
  '/_authenticated/candidate/jobs/saved': typeof AuthenticatedCandidateJobsSavedRoute
  '/_authenticated/candidate/messages/$conversationId': typeof AuthenticatedCandidateMessagesConversationIdRoute
  '/_authenticated/candidate/notifications/$id': typeof AuthenticatedCandidateNotificationsIdRoute
  '/_authenticated/recruiter/applications/$id': typeof AuthenticatedRecruiterApplicationsIdRoute
  '/_authenticated/recruiter/candidates/$id': typeof AuthenticatedRecruiterCandidatesIdRoute
  '/_authenticated/recruiter/candidates/compare': typeof AuthenticatedRecruiterCandidatesCompareRoute
  '/_authenticated/recruiter/candidates/saved': typeof AuthenticatedRecruiterCandidatesSavedRoute
  '/_authenticated/recruiter/jobs/create': typeof AuthenticatedRecruiterJobsCreateRoute
  '/_authenticated/recruiter/messages/$conversationId': typeof AuthenticatedRecruiterMessagesConversationIdRoute
  '/_authenticated/recruiter/notifications/$id': typeof AuthenticatedRecruiterNotificationsIdRoute
  '/_authenticated/recruiter/pipeline/$jobId': typeof AuthenticatedRecruiterPipelineJobIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/_authenticated/candidate/applications/': typeof AuthenticatedCandidateApplicationsIndexRoute
  '/_authenticated/candidate/jobs/': typeof AuthenticatedCandidateJobsIndexRoute
  '/_authenticated/candidate/messages/': typeof AuthenticatedCandidateMessagesIndexRoute
  '/_authenticated/candidate/notifications/': typeof AuthenticatedCandidateNotificationsIndexRoute
  '/_authenticated/recruiter/applications/': typeof AuthenticatedRecruiterApplicationsIndexRoute
  '/_authenticated/recruiter/candidates/': typeof AuthenticatedRecruiterCandidatesIndexRoute
  '/_authenticated/recruiter/jobs/': typeof AuthenticatedRecruiterJobsIndexRoute
  '/_authenticated/recruiter/messages/': typeof AuthenticatedRecruiterMessagesIndexRoute
  '/_authenticated/recruiter/notifications/': typeof AuthenticatedRecruiterNotificationsIndexRoute
  '/_authenticated/recruiter/pipeline/': typeof AuthenticatedRecruiterPipelineIndexRoute
  '/_authenticated/recruiter/jobs/$id/edit': typeof AuthenticatedRecruiterJobsIdEditRoute
  '/_authenticated/recruiter/jobs/$id/preview': typeof AuthenticatedRecruiterJobsIdPreviewRoute
  '/_authenticated/recruiter/jobs/$id/': typeof AuthenticatedRecruiterJobsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/community-guidelines'
    | '/contact'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/unauthorized'
    | '/candidate'
    | '/recruiter'
    | '/auth/callback'
    | '/admin/analytics'
    | '/admin/reports'
    | '/candidate/analytics'
    | '/candidate/applications'
    | '/candidate/career'
    | '/candidate/dashboard'
    | '/candidate/jobs'
    | '/candidate/messages'
    | '/candidate/notifications'
    | '/candidate/onboarding'
    | '/candidate/profile'
    | '/candidate/recommendations'
    | '/candidate/saved-jobs'
    | '/candidate/settings'
    | '/notifications/$id'
    | '/recruiter/analytics'
    | '/recruiter/applications'
    | '/recruiter/candidates'
    | '/recruiter/company'
    | '/recruiter/dashboard'
    | '/recruiter/jobs'
    | '/recruiter/messages'
    | '/recruiter/notifications'
    | '/recruiter/onboarding'
    | '/recruiter/pipeline'
    | '/recruiter/profile'
    | '/recruiter/recommendations'
    | '/recruiter/settings'
    | '/candidate/'
    | '/notifications/'
    | '/recruiter/'
    | '/candidate/applications/$id'
    | '/candidate/jobs/$id'
    | '/candidate/jobs/compare'
    | '/candidate/jobs/saved'
    | '/candidate/messages/$conversationId'
    | '/candidate/notifications/$id'
    | '/recruiter/applications/$id'
    | '/recruiter/candidates/$id'
    | '/recruiter/candidates/compare'
    | '/recruiter/candidates/saved'
    | '/recruiter/jobs/create'
    | '/recruiter/messages/$conversationId'
    | '/recruiter/notifications/$id'
    | '/recruiter/pipeline/$jobId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/candidate/applications/'
    | '/candidate/jobs/'
    | '/candidate/messages/'
    | '/candidate/notifications/'
    | '/recruiter/applications/'
    | '/recruiter/candidates/'
    | '/recruiter/jobs/'
    | '/recruiter/messages/'
    | '/recruiter/notifications/'
    | '/recruiter/pipeline/'
    | '/recruiter/jobs/$id/edit'
    | '/recruiter/jobs/$id/preview'
    | '/recruiter/jobs/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/community-guidelines'
    | '/contact'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/unauthorized'
    | '/auth/callback'
    | '/admin/analytics'
    | '/admin/reports'
    | '/candidate/analytics'
    | '/candidate/career'
    | '/candidate/dashboard'
    | '/candidate/onboarding'
    | '/candidate/profile'
    | '/candidate/recommendations'
    | '/candidate/saved-jobs'
    | '/candidate/settings'
    | '/notifications/$id'
    | '/recruiter/analytics'
    | '/recruiter/company'
    | '/recruiter/dashboard'
    | '/recruiter/onboarding'
    | '/recruiter/profile'
    | '/recruiter/recommendations'
    | '/recruiter/settings'
    | '/candidate'
    | '/notifications'
    | '/recruiter'
    | '/candidate/applications/$id'
    | '/candidate/jobs/$id'
    | '/candidate/jobs/compare'
    | '/candidate/jobs/saved'
    | '/candidate/messages/$conversationId'
    | '/candidate/notifications/$id'
    | '/recruiter/applications/$id'
    | '/recruiter/candidates/$id'
    | '/recruiter/candidates/compare'
    | '/recruiter/candidates/saved'
    | '/recruiter/jobs/create'
    | '/recruiter/messages/$conversationId'
    | '/recruiter/notifications/$id'
    | '/recruiter/pipeline/$jobId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/candidate/applications'
    | '/candidate/jobs'
    | '/candidate/messages'
    | '/candidate/notifications'
    | '/recruiter/applications'
    | '/recruiter/candidates'
    | '/recruiter/jobs'
    | '/recruiter/messages'
    | '/recruiter/notifications'
    | '/recruiter/pipeline'
    | '/recruiter/jobs/$id/edit'
    | '/recruiter/jobs/$id/preview'
    | '/recruiter/jobs/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/community-guidelines'
    | '/contact'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/unauthorized'
    | '/_authenticated/candidate'
    | '/_authenticated/recruiter'
    | '/auth/callback'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/reports'
    | '/_authenticated/candidate/analytics'
    | '/_authenticated/candidate/applications'
    | '/_authenticated/candidate/career'
    | '/_authenticated/candidate/dashboard'
    | '/_authenticated/candidate/jobs'
    | '/_authenticated/candidate/messages'
    | '/_authenticated/candidate/notifications'
    | '/_authenticated/candidate/onboarding'
    | '/_authenticated/candidate/profile'
    | '/_authenticated/candidate/recommendations'
    | '/_authenticated/candidate/saved-jobs'
    | '/_authenticated/candidate/settings'
    | '/_authenticated/notifications/$id'
    | '/_authenticated/recruiter/analytics'
    | '/_authenticated/recruiter/applications'
    | '/_authenticated/recruiter/candidates'
    | '/_authenticated/recruiter/company'
    | '/_authenticated/recruiter/dashboard'
    | '/_authenticated/recruiter/jobs'
    | '/_authenticated/recruiter/messages'
    | '/_authenticated/recruiter/notifications'
    | '/_authenticated/recruiter/onboarding'
    | '/_authenticated/recruiter/pipeline'
    | '/_authenticated/recruiter/profile'
    | '/_authenticated/recruiter/recommendations'
    | '/_authenticated/recruiter/settings'
    | '/_authenticated/candidate/'
    | '/_authenticated/notifications/'
    | '/_authenticated/recruiter/'
    | '/_authenticated/candidate/applications/$id'
    | '/_authenticated/candidate/jobs/$id'
    | '/_authenticated/candidate/jobs/compare'
    | '/_authenticated/candidate/jobs/saved'
    | '/_authenticated/candidate/messages/$conversationId'
    | '/_authenticated/candidate/notifications/$id'
    | '/_authenticated/recruiter/applications/$id'
    | '/_authenticated/recruiter/candidates/$id'
    | '/_authenticated/recruiter/candidates/compare'
    | '/_authenticated/recruiter/candidates/saved'
    | '/_authenticated/recruiter/jobs/create'
    | '/_authenticated/recruiter/messages/$conversationId'
    | '/_authenticated/recruiter/notifications/$id'
    | '/_authenticated/recruiter/pipeline/$jobId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/_authenticated/candidate/applications/'
    | '/_authenticated/candidate/jobs/'
    | '/_authenticated/candidate/messages/'
    | '/_authenticated/candidate/notifications/'
    | '/_authenticated/recruiter/applications/'
    | '/_authenticated/recruiter/candidates/'
    | '/_authenticated/recruiter/jobs/'
    | '/_authenticated/recruiter/messages/'
    | '/_authenticated/recruiter/notifications/'
    | '/_authenticated/recruiter/pipeline/'
    | '/_authenticated/recruiter/jobs/$id/edit'
    | '/_authenticated/recruiter/jobs/$id/preview'
    | '/_authenticated/recruiter/jobs/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  CommunityGuidelinesRoute: typeof CommunityGuidelinesRoute
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-guidelines': {
      id: '/community-guidelines'
      path: '/community-guidelines'
      fullPath: '/community-guidelines'
      preLoaderRoute: typeof CommunityGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/candidate': {
      id: '/_authenticated/candidate'
      path: '/candidate'
      fullPath: '/candidate'
      preLoaderRoute: typeof AuthenticatedCandidateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recruiter': {
      id: '/_authenticated/recruiter'
      path: '/recruiter'
      fullPath: '/recruiter'
      preLoaderRoute: typeof AuthenticatedRecruiterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidate/': {
      id: '/_authenticated/candidate/'
      path: '/'
      fullPath: '/candidate/'
      preLoaderRoute: typeof AuthenticatedCandidateIndexRouteImport
      parentRoute: typeof AuthenticatedCandidateRoute
    }
    '/_authenticated/candidate/analytics': {
      id: '/_authenticated/candidate/analytics'
      path: '/analytics'
      fullPath: '/candidate/analytics'
      preLoaderRoute: typeof AuthenticatedCandidateAnalyticsRouteImport
      parentRoute: typeof AuthenticatedCandidateRoute
    }
    '/_authenticated/candidate/applications': {
      id: '/_authenticated/candidate/applications'
      path: '/applications'
      fullPath: '/candidate/applications'
      preLoaderRoute: typeof AuthenticatedCandidateApplicationsRouteImport
      parentRoute: typeof AuthenticatedCandidateRoute
    }
    '/_authenticated/candidate/career': {
      id: '/_authenticated/candidate/career'
      path: '/career'
      fullPath: '/candidate/career'
      preLoaderRoute: typeof AuthenticatedCandidateCareerRouteImport
      parentRoute: typeof AuthenticatedCandidateRoute
    }
    '/_authenticated/candidate/dashboard': {
      id: '/_authenticated/candidate/dashboard'
      path: '/dashboard'
      fullPath: '/candidate/dashboard'
      preLoaderRoute: typeof AuthenticatedCandidateDashboardRouteImport
      parentRoute: typeof AuthenticatedCandidateRoute
    }
    '/_authenticated/candidate/jobs': {
      id: '/_authenticated/candidate/jobs'
      path: '/jobs'
      fullPath: '/candidate/jobs'
      preLoaderRoute: typeof AuthenticatedCandidateJobsRouteImport
      parentRoute: typeof AuthenticatedCandidateRoute
    }
    '/_authenticated/candidate/messages': {
      id: '/_authenticated/candidate/messages'
      path: '/messages'
      fullPath: '/candidate/messages'
      preLoaderRoute: typeof AuthenticatedCandidateMessagesRouteImport
      parentRoute: typeof AuthenticatedCandidateRoute
    }
    '/_authenticated/candidate/notifications': {
      id: '/_authenticated/candidate/notifications'
      path: '/notifications'
      fullPath: '/candidate/notifications'
      preLoaderRoute: typeof AuthenticatedCandidateNotificationsRouteImport
      parentRoute: typeof AuthenticatedCandidateRoute
    }
    '/_authenticated/candidate/onboarding': {
      id: '/_authenticated/candidate/onboarding'
      path: '/onboarding'
      fullPath: '/candidate/onboarding'
      preLoaderRoute: typeof AuthenticatedCandidateOnboardingRouteImport
      parentRoute: typeof AuthenticatedCandidateRoute
    }
    '/_authenticated/candidate/profile': {
      id: '/_authenticated/candidate/profile'
      path: '/profile'
      fullPath: '/candidate/profile'
      preLoaderRoute: typeof AuthenticatedCandidateProfileRouteImport
      parentRoute: typeof AuthenticatedCandidateRoute
    }
    '/_authenticated/candidate/recommendations': {
      id: '/_authenticated/candidate/recommendations'
      path: '/recommendations'
      fullPath: '/candidate/recommendations'
      preLoaderRoute: typeof AuthenticatedCandidateRecommendationsRouteImport
      parentRoute: typeof AuthenticatedCandidateRoute
    }
    '/_authenticated/candidate/saved-jobs': {
      id: '/_authenticated/candidate/saved-jobs'
      path: '/saved-jobs'
      fullPath: '/candidate/saved-jobs'
      preLoaderRoute: typeof AuthenticatedCandidateSavedJobsRouteImport
      parentRoute: typeof AuthenticatedCandidateRoute
    }
    '/_authenticated/candidate/settings': {
      id: '/_authenticated/candidate/settings'
      path: '/settings'
      fullPath: '/candidate/settings'
      preLoaderRoute: typeof AuthenticatedCandidateSettingsRouteImport
      parentRoute: typeof AuthenticatedCandidateRoute
    }
    '/_authenticated/notifications/': {
      id: '/_authenticated/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof AuthenticatedNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications/$id': {
      id: '/_authenticated/notifications/$id'
      path: '/notifications/$id'
      fullPath: '/notifications/$id'
      preLoaderRoute: typeof AuthenticatedNotificationsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recruiter/': {
      id: '/_authenticated/recruiter/'
      path: '/'
      fullPath: '/recruiter/'
      preLoaderRoute: typeof AuthenticatedRecruiterIndexRouteImport
      parentRoute: typeof AuthenticatedRecruiterRoute
    }
    '/_authenticated/recruiter/analytics': {
      id: '/_authenticated/recruiter/analytics'
      path: '/analytics'
      fullPath: '/recruiter/analytics'
      preLoaderRoute: typeof AuthenticatedRecruiterAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRecruiterRoute
    }
    '/_authenticated/recruiter/applications': {
      id: '/_authenticated/recruiter/applications'
      path: '/applications'
      fullPath: '/recruiter/applications'
      preLoaderRoute: typeof AuthenticatedRecruiterApplicationsRouteImport
      parentRoute: typeof AuthenticatedRecruiterRoute
    }
    '/_authenticated/recruiter/candidates': {
      id: '/_authenticated/recruiter/candidates'
      path: '/candidates'
      fullPath: '/recruiter/candidates'
      preLoaderRoute: typeof AuthenticatedRecruiterCandidatesRouteImport
      parentRoute: typeof AuthenticatedRecruiterRoute
    }
    '/_authenticated/recruiter/company': {
      id: '/_authenticated/recruiter/company'
      path: '/company'
      fullPath: '/recruiter/company'
      preLoaderRoute: typeof AuthenticatedRecruiterCompanyRouteImport
      parentRoute: typeof AuthenticatedRecruiterRoute
    }
    '/_authenticated/recruiter/dashboard': {
      id: '/_authenticated/recruiter/dashboard'
      path: '/dashboard'
      fullPath: '/recruiter/dashboard'
      preLoaderRoute: typeof AuthenticatedRecruiterDashboardRouteImport
      parentRoute: typeof AuthenticatedRecruiterRoute
    }
    '/_authenticated/recruiter/jobs': {
      id: '/_authenticated/recruiter/jobs'
      path: '/jobs'
      fullPath: '/recruiter/jobs'
      preLoaderRoute: typeof AuthenticatedRecruiterJobsRouteImport
      parentRoute: typeof AuthenticatedRecruiterRoute
    }
    '/_authenticated/recruiter/messages': {
      id: '/_authenticated/recruiter/messages'
      path: '/messages'
      fullPath: '/recruiter/messages'
      preLoaderRoute: typeof AuthenticatedRecruiterMessagesRouteImport
      parentRoute: typeof AuthenticatedRecruiterRoute
    }
    '/_authenticated/recruiter/notifications': {
      id: '/_authenticated/recruiter/notifications'
      path: '/notifications'
      fullPath: '/recruiter/notifications'
      preLoaderRoute: typeof AuthenticatedRecruiterNotificationsRouteImport
      parentRoute: typeof AuthenticatedRecruiterRoute
    }
    '/_authenticated/recruiter/onboarding': {
      id: '/_authenticated/recruiter/onboarding'
      path: '/onboarding'
      fullPath: '/recruiter/onboarding'
      preLoaderRoute: typeof AuthenticatedRecruiterOnboardingRouteImport
      parentRoute: typeof AuthenticatedRecruiterRoute
    }
    '/_authenticated/recruiter/pipeline': {
      id: '/_authenticated/recruiter/pipeline'
      path: '/pipeline'
      fullPath: '/recruiter/pipeline'
      preLoaderRoute: typeof AuthenticatedRecruiterPipelineRouteImport
      parentRoute: typeof AuthenticatedRecruiterRoute
    }
    '/_authenticated/recruiter/profile': {
      id: '/_authenticated/recruiter/profile'
      path: '/profile'
      fullPath: '/recruiter/profile'
      preLoaderRoute: typeof AuthenticatedRecruiterProfileRouteImport
      parentRoute: typeof AuthenticatedRecruiterRoute
    }
    '/_authenticated/recruiter/recommendations': {
      id: '/_authenticated/recruiter/recommendations'
      path: '/recommendations'
      fullPath: '/recruiter/recommendations'
      preLoaderRoute: typeof AuthenticatedRecruiterRecommendationsRouteImport
      parentRoute: typeof AuthenticatedRecruiterRoute
    }
    '/_authenticated/recruiter/settings': {
      id: '/_authenticated/recruiter/settings'
      path: '/settings'
      fullPath: '/recruiter/settings'
      preLoaderRoute: typeof AuthenticatedRecruiterSettingsRouteImport
      parentRoute: typeof AuthenticatedRecruiterRoute
    }
    '/_authenticated/candidate/applications/': {
      id: '/_authenticated/candidate/applications/'
      path: '/'
      fullPath: '/candidate/applications/'
      preLoaderRoute: typeof AuthenticatedCandidateApplicationsIndexRouteImport
      parentRoute: typeof AuthenticatedCandidateApplicationsRoute
    }
    '/_authenticated/candidate/applications/$id': {
      id: '/_authenticated/candidate/applications/$id'
      path: '/$id'
      fullPath: '/candidate/applications/$id'
      preLoaderRoute: typeof AuthenticatedCandidateApplicationsIdRouteImport
      parentRoute: typeof AuthenticatedCandidateApplicationsRoute
    }
    '/_authenticated/candidate/jobs/': {
      id: '/_authenticated/candidate/jobs/'
      path: '/'
      fullPath: '/candidate/jobs/'
      preLoaderRoute: typeof AuthenticatedCandidateJobsIndexRouteImport
      parentRoute: typeof AuthenticatedCandidateJobsRoute
    }
    '/_authenticated/candidate/jobs/$id': {
      id: '/_authenticated/candidate/jobs/$id'
      path: '/$id'
      fullPath: '/candidate/jobs/$id'
      preLoaderRoute: typeof AuthenticatedCandidateJobsIdRouteImport
      parentRoute: typeof AuthenticatedCandidateJobsRoute
    }
    '/_authenticated/candidate/jobs/compare': {
      id: '/_authenticated/candidate/jobs/compare'
      path: '/compare'
      fullPath: '/candidate/jobs/compare'
      preLoaderRoute: typeof AuthenticatedCandidateJobsCompareRouteImport
      parentRoute: typeof AuthenticatedCandidateJobsRoute
    }
    '/_authenticated/candidate/jobs/saved': {
      id: '/_authenticated/candidate/jobs/saved'
      path: '/saved'
      fullPath: '/candidate/jobs/saved'
      preLoaderRoute: typeof AuthenticatedCandidateJobsSavedRouteImport
      parentRoute: typeof AuthenticatedCandidateJobsRoute
    }
    '/_authenticated/candidate/messages/': {
      id: '/_authenticated/candidate/messages/'
      path: '/'
      fullPath: '/candidate/messages/'
      preLoaderRoute: typeof AuthenticatedCandidateMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedCandidateMessagesRoute
    }
    '/_authenticated/candidate/messages/$conversationId': {
      id: '/_authenticated/candidate/messages/$conversationId'
      path: '/$conversationId'
      fullPath: '/candidate/messages/$conversationId'
      preLoaderRoute: typeof AuthenticatedCandidateMessagesConversationIdRouteImport
      parentRoute: typeof AuthenticatedCandidateMessagesRoute
    }
    '/_authenticated/candidate/notifications/': {
      id: '/_authenticated/candidate/notifications/'
      path: '/'
      fullPath: '/candidate/notifications/'
      preLoaderRoute: typeof AuthenticatedCandidateNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedCandidateNotificationsRoute
    }
    '/_authenticated/candidate/notifications/$id': {
      id: '/_authenticated/candidate/notifications/$id'
      path: '/$id'
      fullPath: '/candidate/notifications/$id'
      preLoaderRoute: typeof AuthenticatedCandidateNotificationsIdRouteImport
      parentRoute: typeof AuthenticatedCandidateNotificationsRoute
    }
    '/_authenticated/recruiter/applications/': {
      id: '/_authenticated/recruiter/applications/'
      path: '/'
      fullPath: '/recruiter/applications/'
      preLoaderRoute: typeof AuthenticatedRecruiterApplicationsIndexRouteImport
      parentRoute: typeof AuthenticatedRecruiterApplicationsRoute
    }
    '/_authenticated/recruiter/applications/$id': {
      id: '/_authenticated/recruiter/applications/$id'
      path: '/$id'
      fullPath: '/recruiter/applications/$id'
      preLoaderRoute: typeof AuthenticatedRecruiterApplicationsIdRouteImport
      parentRoute: typeof AuthenticatedRecruiterApplicationsRoute
    }
    '/_authenticated/recruiter/candidates/': {
      id: '/_authenticated/recruiter/candidates/'
      path: '/'
      fullPath: '/recruiter/candidates/'
      preLoaderRoute: typeof AuthenticatedRecruiterCandidatesIndexRouteImport
      parentRoute: typeof AuthenticatedRecruiterCandidatesRoute
    }
    '/_authenticated/recruiter/candidates/$id': {
      id: '/_authenticated/recruiter/candidates/$id'
      path: '/$id'
      fullPath: '/recruiter/candidates/$id'
      preLoaderRoute: typeof AuthenticatedRecruiterCandidatesIdRouteImport
      parentRoute: typeof AuthenticatedRecruiterCandidatesRoute
    }
    '/_authenticated/recruiter/candidates/compare': {
      id: '/_authenticated/recruiter/candidates/compare'
      path: '/compare'
      fullPath: '/recruiter/candidates/compare'
      preLoaderRoute: typeof AuthenticatedRecruiterCandidatesCompareRouteImport
      parentRoute: typeof AuthenticatedRecruiterCandidatesRoute
    }
    '/_authenticated/recruiter/candidates/saved': {
      id: '/_authenticated/recruiter/candidates/saved'
      path: '/saved'
      fullPath: '/recruiter/candidates/saved'
      preLoaderRoute: typeof AuthenticatedRecruiterCandidatesSavedRouteImport
      parentRoute: typeof AuthenticatedRecruiterCandidatesRoute
    }
    '/_authenticated/recruiter/jobs/': {
      id: '/_authenticated/recruiter/jobs/'
      path: '/'
      fullPath: '/recruiter/jobs/'
      preLoaderRoute: typeof AuthenticatedRecruiterJobsIndexRouteImport
      parentRoute: typeof AuthenticatedRecruiterJobsRoute
    }
    '/_authenticated/recruiter/jobs/create': {
      id: '/_authenticated/recruiter/jobs/create'
      path: '/create'
      fullPath: '/recruiter/jobs/create'
      preLoaderRoute: typeof AuthenticatedRecruiterJobsCreateRouteImport
      parentRoute: typeof AuthenticatedRecruiterJobsRoute
    }
    '/_authenticated/recruiter/messages/': {
      id: '/_authenticated/recruiter/messages/'
      path: '/'
      fullPath: '/recruiter/messages/'
      preLoaderRoute: typeof AuthenticatedRecruiterMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedRecruiterMessagesRoute
    }
    '/_authenticated/recruiter/messages/$conversationId': {
      id: '/_authenticated/recruiter/messages/$conversationId'
      path: '/$conversationId'
      fullPath: '/recruiter/messages/$conversationId'
      preLoaderRoute: typeof AuthenticatedRecruiterMessagesConversationIdRouteImport
      parentRoute: typeof AuthenticatedRecruiterMessagesRoute
    }
    '/_authenticated/recruiter/notifications/': {
      id: '/_authenticated/recruiter/notifications/'
      path: '/'
      fullPath: '/recruiter/notifications/'
      preLoaderRoute: typeof AuthenticatedRecruiterNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedRecruiterNotificationsRoute
    }
    '/_authenticated/recruiter/notifications/$id': {
      id: '/_authenticated/recruiter/notifications/$id'
      path: '/$id'
      fullPath: '/recruiter/notifications/$id'
      preLoaderRoute: typeof AuthenticatedRecruiterNotificationsIdRouteImport
      parentRoute: typeof AuthenticatedRecruiterNotificationsRoute
    }
    '/_authenticated/recruiter/pipeline/': {
      id: '/_authenticated/recruiter/pipeline/'
      path: '/'
      fullPath: '/recruiter/pipeline/'
      preLoaderRoute: typeof AuthenticatedRecruiterPipelineIndexRouteImport
      parentRoute: typeof AuthenticatedRecruiterPipelineRoute
    }
    '/_authenticated/recruiter/pipeline/$jobId': {
      id: '/_authenticated/recruiter/pipeline/$jobId'
      path: '/$jobId'
      fullPath: '/recruiter/pipeline/$jobId'
      preLoaderRoute: typeof AuthenticatedRecruiterPipelineJobIdRouteImport
      parentRoute: typeof AuthenticatedRecruiterPipelineRoute
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/recruiter/jobs/$id/': {
      id: '/_authenticated/recruiter/jobs/$id/'
      path: '/$id'
      fullPath: '/recruiter/jobs/$id/'
      preLoaderRoute: typeof AuthenticatedRecruiterJobsIdIndexRouteImport
      parentRoute: typeof AuthenticatedRecruiterJobsRoute
    }
    '/_authenticated/recruiter/jobs/$id/edit': {
      id: '/_authenticated/recruiter/jobs/$id/edit'
      path: '/$id/edit'
      fullPath: '/recruiter/jobs/$id/edit'
      preLoaderRoute: typeof AuthenticatedRecruiterJobsIdEditRouteImport
      parentRoute: typeof AuthenticatedRecruiterJobsRoute
    }
    '/_authenticated/recruiter/jobs/$id/preview': {
      id: '/_authenticated/recruiter/jobs/$id/preview'
      path: '/$id/preview'
      fullPath: '/recruiter/jobs/$id/preview'
      preLoaderRoute: typeof AuthenticatedRecruiterJobsIdPreviewRouteImport
      parentRoute: typeof AuthenticatedRecruiterJobsRoute
    }
  }
}

interface AuthenticatedCandidateApplicationsRouteChildren {
  AuthenticatedCandidateApplicationsIdRoute: typeof AuthenticatedCandidateApplicationsIdRoute
  AuthenticatedCandidateApplicationsIndexRoute: typeof AuthenticatedCandidateApplicationsIndexRoute
}

const AuthenticatedCandidateApplicationsRouteChildren: AuthenticatedCandidateApplicationsRouteChildren =
  {
    AuthenticatedCandidateApplicationsIdRoute:
      AuthenticatedCandidateApplicationsIdRoute,
    AuthenticatedCandidateApplicationsIndexRoute:
      AuthenticatedCandidateApplicationsIndexRoute,
  }

const AuthenticatedCandidateApplicationsRouteWithChildren =
  AuthenticatedCandidateApplicationsRoute._addFileChildren(
    AuthenticatedCandidateApplicationsRouteChildren,
  )

interface AuthenticatedCandidateJobsRouteChildren {
  AuthenticatedCandidateJobsIdRoute: typeof AuthenticatedCandidateJobsIdRoute
  AuthenticatedCandidateJobsCompareRoute: typeof AuthenticatedCandidateJobsCompareRoute
  AuthenticatedCandidateJobsSavedRoute: typeof AuthenticatedCandidateJobsSavedRoute
  AuthenticatedCandidateJobsIndexRoute: typeof AuthenticatedCandidateJobsIndexRoute
}

const AuthenticatedCandidateJobsRouteChildren: AuthenticatedCandidateJobsRouteChildren =
  {
    AuthenticatedCandidateJobsIdRoute: AuthenticatedCandidateJobsIdRoute,
    AuthenticatedCandidateJobsCompareRoute:
      AuthenticatedCandidateJobsCompareRoute,
    AuthenticatedCandidateJobsSavedRoute: AuthenticatedCandidateJobsSavedRoute,
    AuthenticatedCandidateJobsIndexRoute: AuthenticatedCandidateJobsIndexRoute,
  }

const AuthenticatedCandidateJobsRouteWithChildren =
  AuthenticatedCandidateJobsRoute._addFileChildren(
    AuthenticatedCandidateJobsRouteChildren,
  )

interface AuthenticatedCandidateMessagesRouteChildren {
  AuthenticatedCandidateMessagesConversationIdRoute: typeof AuthenticatedCandidateMessagesConversationIdRoute
  AuthenticatedCandidateMessagesIndexRoute: typeof AuthenticatedCandidateMessagesIndexRoute
}

const AuthenticatedCandidateMessagesRouteChildren: AuthenticatedCandidateMessagesRouteChildren =
  {
    AuthenticatedCandidateMessagesConversationIdRoute:
      AuthenticatedCandidateMessagesConversationIdRoute,
    AuthenticatedCandidateMessagesIndexRoute:
      AuthenticatedCandidateMessagesIndexRoute,
  }

const AuthenticatedCandidateMessagesRouteWithChildren =
  AuthenticatedCandidateMessagesRoute._addFileChildren(
    AuthenticatedCandidateMessagesRouteChildren,
  )

interface AuthenticatedCandidateNotificationsRouteChildren {
  AuthenticatedCandidateNotificationsIdRoute: typeof AuthenticatedCandidateNotificationsIdRoute
  AuthenticatedCandidateNotificationsIndexRoute: typeof AuthenticatedCandidateNotificationsIndexRoute
}

const AuthenticatedCandidateNotificationsRouteChildren: AuthenticatedCandidateNotificationsRouteChildren =
  {
    AuthenticatedCandidateNotificationsIdRoute:
      AuthenticatedCandidateNotificationsIdRoute,
    AuthenticatedCandidateNotificationsIndexRoute:
      AuthenticatedCandidateNotificationsIndexRoute,
  }

const AuthenticatedCandidateNotificationsRouteWithChildren =
  AuthenticatedCandidateNotificationsRoute._addFileChildren(
    AuthenticatedCandidateNotificationsRouteChildren,
  )

interface AuthenticatedCandidateRouteChildren {
  AuthenticatedCandidateAnalyticsRoute: typeof AuthenticatedCandidateAnalyticsRoute
  AuthenticatedCandidateApplicationsRoute: typeof AuthenticatedCandidateApplicationsRouteWithChildren
  AuthenticatedCandidateCareerRoute: typeof AuthenticatedCandidateCareerRoute
  AuthenticatedCandidateDashboardRoute: typeof AuthenticatedCandidateDashboardRoute
  AuthenticatedCandidateJobsRoute: typeof AuthenticatedCandidateJobsRouteWithChildren
  AuthenticatedCandidateMessagesRoute: typeof AuthenticatedCandidateMessagesRouteWithChildren
  AuthenticatedCandidateNotificationsRoute: typeof AuthenticatedCandidateNotificationsRouteWithChildren
  AuthenticatedCandidateOnboardingRoute: typeof AuthenticatedCandidateOnboardingRoute
  AuthenticatedCandidateProfileRoute: typeof AuthenticatedCandidateProfileRoute
  AuthenticatedCandidateRecommendationsRoute: typeof AuthenticatedCandidateRecommendationsRoute
  AuthenticatedCandidateSavedJobsRoute: typeof AuthenticatedCandidateSavedJobsRoute
  AuthenticatedCandidateSettingsRoute: typeof AuthenticatedCandidateSettingsRoute
  AuthenticatedCandidateIndexRoute: typeof AuthenticatedCandidateIndexRoute
}

const AuthenticatedCandidateRouteChildren: AuthenticatedCandidateRouteChildren =
  {
    AuthenticatedCandidateAnalyticsRoute: AuthenticatedCandidateAnalyticsRoute,
    AuthenticatedCandidateApplicationsRoute:
      AuthenticatedCandidateApplicationsRouteWithChildren,
    AuthenticatedCandidateCareerRoute: AuthenticatedCandidateCareerRoute,
    AuthenticatedCandidateDashboardRoute: AuthenticatedCandidateDashboardRoute,
    AuthenticatedCandidateJobsRoute:
      AuthenticatedCandidateJobsRouteWithChildren,
    AuthenticatedCandidateMessagesRoute:
      AuthenticatedCandidateMessagesRouteWithChildren,
    AuthenticatedCandidateNotificationsRoute:
      AuthenticatedCandidateNotificationsRouteWithChildren,
    AuthenticatedCandidateOnboardingRoute:
      AuthenticatedCandidateOnboardingRoute,
    AuthenticatedCandidateProfileRoute: AuthenticatedCandidateProfileRoute,
    AuthenticatedCandidateRecommendationsRoute:
      AuthenticatedCandidateRecommendationsRoute,
    AuthenticatedCandidateSavedJobsRoute: AuthenticatedCandidateSavedJobsRoute,
    AuthenticatedCandidateSettingsRoute: AuthenticatedCandidateSettingsRoute,
    AuthenticatedCandidateIndexRoute: AuthenticatedCandidateIndexRoute,
  }

const AuthenticatedCandidateRouteWithChildren =
  AuthenticatedCandidateRoute._addFileChildren(
    AuthenticatedCandidateRouteChildren,
  )

interface AuthenticatedRecruiterApplicationsRouteChildren {
  AuthenticatedRecruiterApplicationsIdRoute: typeof AuthenticatedRecruiterApplicationsIdRoute
  AuthenticatedRecruiterApplicationsIndexRoute: typeof AuthenticatedRecruiterApplicationsIndexRoute
}

const AuthenticatedRecruiterApplicationsRouteChildren: AuthenticatedRecruiterApplicationsRouteChildren =
  {
    AuthenticatedRecruiterApplicationsIdRoute:
      AuthenticatedRecruiterApplicationsIdRoute,
    AuthenticatedRecruiterApplicationsIndexRoute:
      AuthenticatedRecruiterApplicationsIndexRoute,
  }

const AuthenticatedRecruiterApplicationsRouteWithChildren =
  AuthenticatedRecruiterApplicationsRoute._addFileChildren(
    AuthenticatedRecruiterApplicationsRouteChildren,
  )

interface AuthenticatedRecruiterCandidatesRouteChildren {
  AuthenticatedRecruiterCandidatesIdRoute: typeof AuthenticatedRecruiterCandidatesIdRoute
  AuthenticatedRecruiterCandidatesCompareRoute: typeof AuthenticatedRecruiterCandidatesCompareRoute
  AuthenticatedRecruiterCandidatesSavedRoute: typeof AuthenticatedRecruiterCandidatesSavedRoute
  AuthenticatedRecruiterCandidatesIndexRoute: typeof AuthenticatedRecruiterCandidatesIndexRoute
}

const AuthenticatedRecruiterCandidatesRouteChildren: AuthenticatedRecruiterCandidatesRouteChildren =
  {
    AuthenticatedRecruiterCandidatesIdRoute:
      AuthenticatedRecruiterCandidatesIdRoute,
    AuthenticatedRecruiterCandidatesCompareRoute:
      AuthenticatedRecruiterCandidatesCompareRoute,
    AuthenticatedRecruiterCandidatesSavedRoute:
      AuthenticatedRecruiterCandidatesSavedRoute,
    AuthenticatedRecruiterCandidatesIndexRoute:
      AuthenticatedRecruiterCandidatesIndexRoute,
  }

const AuthenticatedRecruiterCandidatesRouteWithChildren =
  AuthenticatedRecruiterCandidatesRoute._addFileChildren(
    AuthenticatedRecruiterCandidatesRouteChildren,
  )

interface AuthenticatedRecruiterJobsRouteChildren {
  AuthenticatedRecruiterJobsCreateRoute: typeof AuthenticatedRecruiterJobsCreateRoute
  AuthenticatedRecruiterJobsIndexRoute: typeof AuthenticatedRecruiterJobsIndexRoute
  AuthenticatedRecruiterJobsIdEditRoute: typeof AuthenticatedRecruiterJobsIdEditRoute
  AuthenticatedRecruiterJobsIdPreviewRoute: typeof AuthenticatedRecruiterJobsIdPreviewRoute
  AuthenticatedRecruiterJobsIdIndexRoute: typeof AuthenticatedRecruiterJobsIdIndexRoute
}

const AuthenticatedRecruiterJobsRouteChildren: AuthenticatedRecruiterJobsRouteChildren =
  {
    AuthenticatedRecruiterJobsCreateRoute:
      AuthenticatedRecruiterJobsCreateRoute,
    AuthenticatedRecruiterJobsIndexRoute: AuthenticatedRecruiterJobsIndexRoute,
    AuthenticatedRecruiterJobsIdEditRoute:
      AuthenticatedRecruiterJobsIdEditRoute,
    AuthenticatedRecruiterJobsIdPreviewRoute:
      AuthenticatedRecruiterJobsIdPreviewRoute,
    AuthenticatedRecruiterJobsIdIndexRoute:
      AuthenticatedRecruiterJobsIdIndexRoute,
  }

const AuthenticatedRecruiterJobsRouteWithChildren =
  AuthenticatedRecruiterJobsRoute._addFileChildren(
    AuthenticatedRecruiterJobsRouteChildren,
  )

interface AuthenticatedRecruiterMessagesRouteChildren {
  AuthenticatedRecruiterMessagesConversationIdRoute: typeof AuthenticatedRecruiterMessagesConversationIdRoute
  AuthenticatedRecruiterMessagesIndexRoute: typeof AuthenticatedRecruiterMessagesIndexRoute
}

const AuthenticatedRecruiterMessagesRouteChildren: AuthenticatedRecruiterMessagesRouteChildren =
  {
    AuthenticatedRecruiterMessagesConversationIdRoute:
      AuthenticatedRecruiterMessagesConversationIdRoute,
    AuthenticatedRecruiterMessagesIndexRoute:
      AuthenticatedRecruiterMessagesIndexRoute,
  }

const AuthenticatedRecruiterMessagesRouteWithChildren =
  AuthenticatedRecruiterMessagesRoute._addFileChildren(
    AuthenticatedRecruiterMessagesRouteChildren,
  )

interface AuthenticatedRecruiterNotificationsRouteChildren {
  AuthenticatedRecruiterNotificationsIdRoute: typeof AuthenticatedRecruiterNotificationsIdRoute
  AuthenticatedRecruiterNotificationsIndexRoute: typeof AuthenticatedRecruiterNotificationsIndexRoute
}

const AuthenticatedRecruiterNotificationsRouteChildren: AuthenticatedRecruiterNotificationsRouteChildren =
  {
    AuthenticatedRecruiterNotificationsIdRoute:
      AuthenticatedRecruiterNotificationsIdRoute,
    AuthenticatedRecruiterNotificationsIndexRoute:
      AuthenticatedRecruiterNotificationsIndexRoute,
  }

const AuthenticatedRecruiterNotificationsRouteWithChildren =
  AuthenticatedRecruiterNotificationsRoute._addFileChildren(
    AuthenticatedRecruiterNotificationsRouteChildren,
  )

interface AuthenticatedRecruiterPipelineRouteChildren {
  AuthenticatedRecruiterPipelineJobIdRoute: typeof AuthenticatedRecruiterPipelineJobIdRoute
  AuthenticatedRecruiterPipelineIndexRoute: typeof AuthenticatedRecruiterPipelineIndexRoute
}

const AuthenticatedRecruiterPipelineRouteChildren: AuthenticatedRecruiterPipelineRouteChildren =
  {
    AuthenticatedRecruiterPipelineJobIdRoute:
      AuthenticatedRecruiterPipelineJobIdRoute,
    AuthenticatedRecruiterPipelineIndexRoute:
      AuthenticatedRecruiterPipelineIndexRoute,
  }

const AuthenticatedRecruiterPipelineRouteWithChildren =
  AuthenticatedRecruiterPipelineRoute._addFileChildren(
    AuthenticatedRecruiterPipelineRouteChildren,
  )

interface AuthenticatedRecruiterRouteChildren {
  AuthenticatedRecruiterAnalyticsRoute: typeof AuthenticatedRecruiterAnalyticsRoute
  AuthenticatedRecruiterApplicationsRoute: typeof AuthenticatedRecruiterApplicationsRouteWithChildren
  AuthenticatedRecruiterCandidatesRoute: typeof AuthenticatedRecruiterCandidatesRouteWithChildren
  AuthenticatedRecruiterCompanyRoute: typeof AuthenticatedRecruiterCompanyRoute
  AuthenticatedRecruiterDashboardRoute: typeof AuthenticatedRecruiterDashboardRoute
  AuthenticatedRecruiterJobsRoute: typeof AuthenticatedRecruiterJobsRouteWithChildren
  AuthenticatedRecruiterMessagesRoute: typeof AuthenticatedRecruiterMessagesRouteWithChildren
  AuthenticatedRecruiterNotificationsRoute: typeof AuthenticatedRecruiterNotificationsRouteWithChildren
  AuthenticatedRecruiterOnboardingRoute: typeof AuthenticatedRecruiterOnboardingRoute
  AuthenticatedRecruiterPipelineRoute: typeof AuthenticatedRecruiterPipelineRouteWithChildren
  AuthenticatedRecruiterProfileRoute: typeof AuthenticatedRecruiterProfileRoute
  AuthenticatedRecruiterRecommendationsRoute: typeof AuthenticatedRecruiterRecommendationsRoute
  AuthenticatedRecruiterSettingsRoute: typeof AuthenticatedRecruiterSettingsRoute
  AuthenticatedRecruiterIndexRoute: typeof AuthenticatedRecruiterIndexRoute
}

const AuthenticatedRecruiterRouteChildren: AuthenticatedRecruiterRouteChildren =
  {
    AuthenticatedRecruiterAnalyticsRoute: AuthenticatedRecruiterAnalyticsRoute,
    AuthenticatedRecruiterApplicationsRoute:
      AuthenticatedRecruiterApplicationsRouteWithChildren,
    AuthenticatedRecruiterCandidatesRoute:
      AuthenticatedRecruiterCandidatesRouteWithChildren,
    AuthenticatedRecruiterCompanyRoute: AuthenticatedRecruiterCompanyRoute,
    AuthenticatedRecruiterDashboardRoute: AuthenticatedRecruiterDashboardRoute,
    AuthenticatedRecruiterJobsRoute:
      AuthenticatedRecruiterJobsRouteWithChildren,
    AuthenticatedRecruiterMessagesRoute:
      AuthenticatedRecruiterMessagesRouteWithChildren,
    AuthenticatedRecruiterNotificationsRoute:
      AuthenticatedRecruiterNotificationsRouteWithChildren,
    AuthenticatedRecruiterOnboardingRoute:
      AuthenticatedRecruiterOnboardingRoute,
    AuthenticatedRecruiterPipelineRoute:
      AuthenticatedRecruiterPipelineRouteWithChildren,
    AuthenticatedRecruiterProfileRoute: AuthenticatedRecruiterProfileRoute,
    AuthenticatedRecruiterRecommendationsRoute:
      AuthenticatedRecruiterRecommendationsRoute,
    AuthenticatedRecruiterSettingsRoute: AuthenticatedRecruiterSettingsRoute,
    AuthenticatedRecruiterIndexRoute: AuthenticatedRecruiterIndexRoute,
  }

const AuthenticatedRecruiterRouteWithChildren =
  AuthenticatedRecruiterRoute._addFileChildren(
    AuthenticatedRecruiterRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCandidateRoute: typeof AuthenticatedCandidateRouteWithChildren
  AuthenticatedRecruiterRoute: typeof AuthenticatedRecruiterRouteWithChildren
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedNotificationsIdRoute: typeof AuthenticatedNotificationsIdRoute
  AuthenticatedNotificationsIndexRoute: typeof AuthenticatedNotificationsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCandidateRoute: AuthenticatedCandidateRouteWithChildren,
  AuthenticatedRecruiterRoute: AuthenticatedRecruiterRouteWithChildren,
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedNotificationsIdRoute: AuthenticatedNotificationsIdRoute,
  AuthenticatedNotificationsIndexRoute: AuthenticatedNotificationsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  CommunityGuidelinesRoute: CommunityGuidelinesRoute,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
